


#used for API server
#datasource1:
#    #class: core\datasources\RestDataSource
#    class: extensions\api\datasources\RestAPIDatasource
#    credentials:
#        baseUrl: http://127.0.0.1:8070
#        format: json
#        headers:
#            serverName: api-server
#            serverAuth: $1$lIDKkGiyJVn2bZSQdxwEYW0


database:
#    host: localhost
#    username: username_here
#    password: password_here
#    dbName: db_name_here


BHDB6_couchbase:
    class: 'Gossamer\Pesedget\Extensions\Couchbase\Connections\CouchbaseDBConnection'
    credentials:
        host: 192.168.1.71
        username: user
        password: passwd
        dbName: mydb
        authentication: true




#default:
default: BHDB6_couchbase
