<?php
/**
 * Created by PhpStorm.
 * User: Travis Junck
 * Date: 2019-11-17
 * Time: 9:41 PM
 */

namespace Gossamer\Ra\Security\Filters;


use Gossamer\Core\Components\Security\Traits\GetLoggedInMemberTrait;
use Gossamer\Horus\Filters\AbstractFilter;
use Gossamer\Horus\Filters\FilterChain;
use Gossamer\Horus\Http\HttpRequest;
use Gossamer\Horus\Http\HttpResponse;

class AddClientToResponseFilter extends AbstractFilter
{
    use GetLoggedInMemberTrait;

    public function execute(HttpRequest &$request, HttpResponse &$response, FilterChain &$chain)
    {
        if (!is_null($this->httpRequest->getAttribute('Client'))) {

            $this->httpResponse->setAttribute('Client', $this->httpRequest->getAttribute('Client')->toArray());
        }elseif(!is_null(getSession('_security_secured_area'))) {
            $token = unserialize(getSession('_security_secured_area'));

            $this->httpResponse->setAttribute('Client', $token->getClient()->toArray() );
        }else {
            $this->httpResponse->setAttribute('Client',$this->getLoggedInMember()->toArray());
        }

        parent::execute($request, $response, $chain); // TODO: Change the autogenerated stub
    }

}